# ── SUPABASE (POSTGRESQL ONLINE DATABASE PROFILE) ──
spring.datasource.url=jdbc:postgresql://${DB_HOST:db.xmegdperrxmprgxqvkaq.supabase.co}:${DB_PORT:5432}/${DB_NAME:postgres}?sslmode=require
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:5RBONt4L9dojNB1G}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
